// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlXLDw00R62lKHtR-ZNx0-ZfOx--uFaUI',
    appId: '1:442519218501:web:592c066c4de66a5187762c',
    messagingSenderId: '442519218501',
    projectId: 'exchnage-wallet-kurd',
    authDomain: 'exchnage-wallet-kurd.firebaseapp.com',
    storageBucket: 'exchnage-wallet-kurd.appspot.com',
    measurementId: 'G-6HHEPB25D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYPu7eUiCA-osFo7S-RwcdhWERoMy0erw',
    appId: '1:442519218501:android:1911535a60385ee387762c',
    messagingSenderId: '442519218501',
    projectId: 'exchnage-wallet-kurd',
    storageBucket: 'exchnage-wallet-kurd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPf32xZoEqPZYES4fYw58Ka8fh79XXbu0',
    appId: '1:442519218501:ios:324bf83278fd55f187762c',
    messagingSenderId: '442519218501',
    projectId: 'exchnage-wallet-kurd',
    storageBucket: 'exchnage-wallet-kurd.appspot.com',
    iosBundleId: 'com.example.exchnageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPf32xZoEqPZYES4fYw58Ka8fh79XXbu0',
    appId: '1:442519218501:ios:324bf83278fd55f187762c',
    messagingSenderId: '442519218501',
    projectId: 'exchnage-wallet-kurd',
    storageBucket: 'exchnage-wallet-kurd.appspot.com',
    iosBundleId: 'com.example.exchnageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlXLDw00R62lKHtR-ZNx0-ZfOx--uFaUI',
    appId: '1:442519218501:web:d91639654f8fc55187762c',
    messagingSenderId: '442519218501',
    projectId: 'exchnage-wallet-kurd',
    authDomain: 'exchnage-wallet-kurd.firebaseapp.com',
    storageBucket: 'exchnage-wallet-kurd.appspot.com',
    measurementId: 'G-69QVQGD4M3',
  );
}
